services:
  postgres:
    image: postgres:16
    env_file: ./server/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  api:
    build: ./server
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres

  client:
    build: ./client
    volumes:
      - ./client:/app
      - client_nodes:/app/node_modules
      - client_next_cache:/app/.next
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./infra/nginx.config:/etc/nginx/conf.d/default.conf:ro
      - infra_nginx:/var/log/nginx
    depends_on:
      - client
      - api

volumes:
  pgdata:
  client_nodes:
  client_next_cache:
  infra_nginx: