services:
  postgres:
    image: postgres:16
    env_file: ./server/.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d

  api:
    build: ./server
    env_file: ./server/.env
    ports:
      - "8001:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres

  client:
    build: ./client
    ports:
      - "3001:3000"
    volumes:
      - ./client:/app
      - client_nodes:/app/node_modules
      - client_next_cache:/app/.next
    environment:
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true

volumes:
  pgdata:
  ollama_data:
  client_nodes:
  client_next_cache: